apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: api
          image: api:latest
          command: ["python3", "app.py"]
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
