apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "project"
  template:
    metadata:
      labels:
        app: "project"
    spec:
      containers:
        - name: hypervisor
          image: hypervisor
          command: ["python3", "hypervisor.py"]
          ports:
            - containerPort: 8081
        - name: expert1
          image: expert
          command: ["python3", "expert.py"]
          ports:
            - containerPort: 8081
