apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    app: project
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
        run: rabbitmq

    spec:
      containers:
        - name: hypervisor
          image: hypervisor:latest
          command: ["python3", "hypervisor.py"]
          ports:
            - containerPort: 8081
          imagePullPolicy: Never

        - name: expert1
          image: expert:latest
          command: ["python3", "expert.py"]
          ports:
            - containerPort: 8081
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: OPENAI_API_KEY
          imagePullPolicy: Never
