apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1WemFKanVsN09HdXhBM0NFYVdxaEZZN2w0YXdkMWE2OWVQUHdLRlNqekRKNlNtSWZIblh3YUxISk4zQXkwLUxxY3lUdkt2U2Y5RVQzQmxia0ZKeFBhb3lURGZYSzlxV3hsVEFXQ0diMXU2c2dvM1I4cFNFeXhYQkozTjNsZGlRRWJYTU15Tk5mZDF0THVoOFNDd2FseDd2NUI0Z0E=
